apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: macwlu/sovr-app:api-gateway
        ports:
        - containerPort: 8079
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: CONFIG_SERVER_URL
          value: "http://config-server:8888"
        - name: EUREKA_SERVER_URL
          value: "http://eureka-server:8761/eureka"
      imagePullSecrets:
        - name: my-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: 8079
    targetPort: 8079
  type: LoadBalancer
