server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:macwlu97/sovr-app-config.git
          username: xxx
          password: yyy
          searchPaths:
            - service1  # Katalog z konfiguracją dla service1
            - service2  # Katalog z konfiguracją dla service2
