server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          default-label: master
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          searchPaths:
            - service1  # Katalog z konfiguracją dla service1
            - service2  # Katalog z konfiguracją dla service2

logging:
  level:
    org.springframework.cloud.config: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
