spring:
  application:
    name: service1

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}  # Określenie, który profil ma być aktywny

  cloud:
    discovery:
      enabled: true
    config:
      uri: ${CONFIG_SERVER_URL}

  config:
    import: configserver:${CONFIG_SERVER_URL}

server:
  port: 8081  # Port, na którym będzie nasłuchiwać Service1

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics  # Umożliwia dostęp do tych endpointów
      base-path: /actuator  # Domyślny path dla Actuatora (np. /actuator/health)
  endpoint:
    health:
      show-details: always  # Ustawienie, aby zawsze pokazywał szczegóły stanu zdrowia aplikacji
    metrics:
      enabled: true  # Włącza metryki aplikacji
